<?php

/*
 * Copyright 2004-2015, AfterLogic Corp.
 * Licensed under AGPLv3 license or AfterLogic license
 * if commercial version of the product was purchased.
 * See the LICENSE file for a full license statement.
 */

// autoload.php generated by Composer
require_once __DIR__ . '/composer' . '/autoload_real.php';

return ComposerAutoloaderInit::getLoader();
