<?php

/*
 * Copyright 2004-2014, AfterLogic Corp.
 * Licensed under AGPLv3 license or AfterLogic license
 * if commerical version of the product was purchased.
 * See the LICENSE file for a full license statement.
 */

	define('PRO_MODE_LICESING', 'licensing');

	define('PRO_SWITCHER_MODE_CHANNEL', 'settings');
	define('PRO_SWITCHER_MODE_TENANT', 'settings');
	define('PRO_SWITCHER_MODE_EDIT_CALENDAR', 'editcalendar');

	/* langs */

	define('PRO_MODE_LICESING_NAME', CApi::I18N('ADMIN_PANEL/SUBTABNAME_LICENSING'));
	define('PRO_SWITCHER_MODE_CHANNEL_NAME', CApi::I18N('ADMIN_PANEL/SWITCHER_MODE_CHANNEL_NAME'));
	define('PRO_SWITCHER_MODE_TENANT_NAME', CApi::I18N('ADMIN_PANEL/SWITCHER_MODE_TENANT_NAME'));
	define('PRO_SWITCHER_MODE_EDIT_CALENDAR_NAME', CApi::I18N('ADMIN_PANEL/EDIT_DOMAIN_CALENDAR_NAME'));

	define('PRO_LANG_NOTENANTS', CApi::I18N('ADMIN_PANEL/INFO_NOTENANTS'));
	define('PRO_LANG_TENANTS_RESULTEMPTY', CApi::I18N('ADMIN_PANEL/INFO_TENANTS_NOT_FOUND'));
	define('PRO_LANG_TENANT_EXIST', CApi::I18N('ADMIN_PANEL/MSG_TENANT_EXIST'));

	define('PRO_LANG_NOCHANNELS', CApi::I18N('ADMIN_PANEL/INFO_NOCHANNELS'));
	define('PRO_LANG_CHANNELS_RESULTEMPTY', CApi::I18N('ADMIN_PANEL/INFO_CHANNELS_NOT_FOUND'));
	define('PRO_LANG_CHANNEL_EXIST', CApi::I18N('ADMIN_PANEL/MSG_CHANNEL_EXIST'));

	define('PRO_LANG_DELETE_SUCCESSFUL', CApi::I18N('ADMIN_PANEL/DELETE_SUCCESSFUL'));
	define('PRO_LANG_DELETE_UNSUCCESSFUL', CApi::I18N('ADMIN_PANEL/DELETE_UNSUCCESSFUL'));

	define('PRO_DEMO_LKEY', 'WM700-DEMO-DEMO-DEMO-DEMO-DEMO-DEMO-123457A');

